<?php

namespace Tests\Feature\app\Http\Controllers;

use App\Enums\TypeUserEnum;
use App\Models\Document;
use App\Models\Group;
use App\Models\GroupHasRepresentative;
use App\Models\TypeUser;
use App\Models\User;
use Faker\Factory as FakerFactory;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\Feature\Utils\LoginUsersTrait;
use Tests\TestCase;

class DocumentControllerTest extends TestCase
{
    use DatabaseTransactions;
    use LoginUsersTrait;

    public function setUp(): void
    {
        $this->faker = FakerFactory::create();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testShouldListAll()
    {
        Document::factory(2)->create();

        $this->login(TypeUserEnum::REPRESENTATIVE);

        $response = $this->get('api/documents');

        $response->assertStatus(200);
        $this->assertCount(2, json_decode($response->getContent(), true));
    }

    public function testShouldListOne()
    {
        $document = Document::factory()->create();
        $this->login(TypeUserEnum::REPRESENTATIVE);

        $response = $this->get(sprintf('api/documents/%s', $document->id));

        $response->assertStatus(200);
        $response->assertJsonStructure($this->getJsonStructure());
    }

    public function testNotShouldListOneWhenNotFoundDocument()
    {
        $this->login(TypeUserEnum::REPRESENTATIVE);

        $response = $this->get(sprintf('api/documents/%s', 100));

        $response->assertStatus(404);
        $this->assertEquals('Documento não encontrado', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldCreate()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();

        $file = UploadedFile::fake()->create('file.pdf');
        $payload = [
            'description' => $this->faker->text,
            'file'        => $file,
        ];

        $response = $this->post(sprintf('/api/group/%s/documents', $group->id), $payload);
        $response->assertStatus(201);
        $response->assertJsonStructure(['file']);
        $response = json_decode($response->getContent(), true);
        $this->assertDatabaseHas('documents', $response);
    }

    public function testShouldNotCreateWhenGroupNotFound()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();

        $payload = [
            'description' => $this->faker->text,
            'file'        => UploadedFile::fake()->create('file.pdf'),
        ];

        $response = $this->post(sprintf('/api/group/%s/documents', 100), $payload);

        $response->assertStatus(404);
        $this->assertEquals('Grupo não encontrado', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldNotCreateWhenIsNotTheRepresentativeOfGroup()
    {
        $typeUser = TypeUser::where('name', TypeUserEnum::REPRESENTATIVE)->first();
        $this->login(TypeUserEnum::REPRESENTATIVE);
        $user1 = User::factory(['type_user_id' => $typeUser->id])->create();
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $user1->id])->create();

        $payload = [
            'description' => $this->faker->text,
            'file'        => UploadedFile::fake()->create('file.pdf'),
        ];

        $response = $this->post(sprintf('/api/group/%s/documents', $group->id), $payload);

        $response->assertStatus(403);
        $this->assertEquals('This action is unauthorized.', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldUpdate()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();
        $document = Document::factory(['group_id' => $group->id])->create();

        $payload = [
            'description' => $this->faker->text,
            'file'        => UploadedFile::fake()->create('file.pdf'),
            'method' => 'PUT',
        ];

        $response = $this->post(sprintf('api/documents/%s', $document->id), $payload);

        $response->assertStatus(200);
        $response->assertJsonStructure(['file']);
        $response = json_decode($response->getContent(), true);
        $this->assertDatabaseHas('documents', $response);
    }

    public function testShouldNotUpdateWhenIsNotTheRepresentativeOfGroup()
    {
        $typeUser = TypeUser::where('name', TypeUserEnum::REPRESENTATIVE)->first();
        $this->login(TypeUserEnum::REPRESENTATIVE);
        $user1 = User::factory(['type_user_id' => $typeUser->id])->create();
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $user1->id])->create();
        $document = Document::factory(['group_id' => $group->id])->create();

        $payload = [
            'description' => $this->faker->text,
            'file'        => UploadedFile::fake()->create('file.pdf'),
        ];

        $response = $this->post(sprintf('api/documents/%s', $document->id), $payload);

        $response->assertStatus(403);
        $this->assertEquals('This action is unauthorized.', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldDelete()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();
        $document = Document::factory(['group_id' => $group->id])->create();

        $response = $this->delete(sprintf('api/group/%s/documents/%s', $group->id, $document->id));

        $response->assertStatus(204);
        $this->assertDatabaseMissing('documents', $document->toArray());
    }

    public function testShouldNotDeleteWhenGroupNotFound()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $user1 = User::factory()->create();
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();
        $document = Document::factory(['group_id' => $group->id])->create();

        $response = $this->delete(sprintf('api/group/%s/documents/%s', 100, $document->id));

        $response->assertStatus(404);
        $this->assertEquals('Grupo não encontrado', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldNotDeleteWhenDocumentNotFound()
    {
        $userRepresentative = $this->login(TypeUserEnum::REPRESENTATIVE);
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $userRepresentative->id])->create();

        $response = $this->delete(sprintf('api/group/%s/documents/%s', $group->id, 100));

        $response->assertStatus(404);
        $this->assertEquals('Documento não encontrado', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldNotDeleteWhenIsNotTheRepresentativeOfGroup()
    {
        $typeUser = TypeUser::where('name', TypeUserEnum::REPRESENTATIVE)->first();
        $this->login(TypeUserEnum::REPRESENTATIVE);
        $user1 = User::factory(['type_user_id' => $typeUser->id])->create();
        $group = Group::factory()->create();
        GroupHasRepresentative::factory(['group_id' => $group->id, 'user_id' => $user1->id])->create();
        $document = Document::factory(['group_id' => $group->id])->create();

        $response = $this->delete(sprintf('api/group/%s/documents/%s', $group->id, $document->id));

        $response->assertStatus(403);
        $this->assertEquals('This action is unauthorized.', json_decode($response->getContent(), true)['errors']);
    }

    public function testShouldDownload()
    {
        $this->login(TypeUserEnum::VIEWER);
        $file = UploadedFile::fake()->create('file.pdf');
        $file =  Storage::disk('local')->put('docs', $file);

        $document = Document::factory()->create(['file' => $file]);

        $response = $this->get("/api/documents/download/{$document->id}");

        $response->assertStatus(200);
        Storage::disk('local')->delete($file);
    }

    private function getJsonStructure(): array
    {
        return [
            'id',
            'name',
            'description',
            'file',
            'created_at',
            'updated_at',
            'group_id',
        ];
    }
}
