version: '3.7'

services:
    plataforma.dev:
        container_name: plataforma.dev
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                APP_ENV: ${APP_ENV}
                XDEBUG_MODE: ${XDEBUG_MODE}
                XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
                XDEBUG_HANDLER: ${XDEBUG_HANDLER}
        volumes:
            - ./:/app
        depends_on:
            - plataforma.db

    plataforma.db:
        container_name: plataforma.db
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: plataform
            PGDATA: /docker/dbdata
        volumes:
            - ./docker/dbdata:/var/lib/postgresql/data
            - ./docker/pgsql:/docker-entrypoint-initdb.d

    nginx:
        container_name: nginx
        build: docker/nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./:/app
        depends_on:
            - plataforma.dev

volumes:
    plataforma.db:

networks:
    bubble:
        external: true
